name: 持续集成

on:
  push:
  pull_request:

jobs:
  rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - name: 检查格式
        run: cargo fmt --check
      - name: 运行测试
        run: cargo test --workspace
      - name: 运行 clippy
        run: cargo clippy --workspace -- -D warnings
